name: Ready to code and deploy

on:
  push:
  workflow_dispatch:

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: copying code
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24.13.1"

      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.9
        with:
          version: "10.31.0"

      - name: Check Node.js version
        run: node -v

      - name: Install dependencies
        run: |
          cd Backend
          pnpm install --frozen-lockfile

      # - name: Install dependencies
      #   run: |
      #     cd frontend
      #     pnpm install --frozen-lockfile

      # - name: Build Backend
      #   run: |
      #     cd Backend
      #     pnpm build

      # - name: Build frontend
      #   run: |
      #     cd frontend
      #     pnpm build

  build-code:
    runs-on: ubuntu-latest
    needs: test-code
    steps:
      - name: Building code
        run: echo "Building code..."

  deploy-code:
    runs-on: ubuntu-latest
    needs: build-code
    steps:
      - name: Deploying code
        run: echo "Deploying code..."
