name: Ready to code and deploy

on:
  push:
  workflow_dispatch:

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: copying code
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.13.1'

      - name: Check Node.js version
        run: node -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Run build
        run: pnpm build
        